# get latest version of Homebrew
update

# update installed formulae
upgrade

# install brews
install wget
install mongodb
install phantomjs

# add cask tap
tap phinze/homebrew-cask

# install cask
install brew-cask

# install apps
cask install alfred
cask install dropbox
cask install google-chrome
cask install google-drive
cask install google-hangouts

cask install sublime-text
cask install virtualbox
cask install vagrant
cask install firefox
cask install toggldesktop
cask install ccmenu

# configure alfred to work with cask apps
cask alfred link

# cleanup
cleanup
